site_name: HelLib
site_description: Library optimizing PySeal for PFGA parallel processing
site_author: Group 8

repo_url: https://github.com/siennaphia/HelLib
edit_uri: https://github.com/siennaphia/HelLib/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
